spring:
  application:
    name: carrental
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: CAR_RENTAL_ADMIN
    password: CAR_RENTAL_LOCAL
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    open-in-view: false
  database:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
  url: jdbc:postgresql://localhost:5432/postgres
  schemas: public
  user: "CAR_RENTAL_ADMIN"
  password: "CAR_RENTAL_LOCAL"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8081

jwt:
  expiration: 28800000
  secret: d0f96f47-cdcf-49a4-8cbf-0465d247871d
