version: '3.3'

networks:
  carrental_network:
    ipam:
      driver: default
      config:
        - subnet: 145.0.0.0/16


services:
  carrental_postgres:
    container_name: carrental_postgres
    image: postgres:13.5
    ports:
      - "5432:5432"
    networks:
      pflege_accounting_network:
        ipv4_address: 145.0.0.2
    environment:
      POSTGRES_USER: "CAR_RENTAL_ADMIN"
      POSTGRES_PASSWORD: "CAR_RENTAL_LOCAL"

  carrental_sonarqube:
    container_name: carrental_sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      carrental_network:
        ipv4_address: 145.0.0.3
    volumes:
      - ./tmp/sonarqube/data:/opt/sonarqube/data
      - ./tmp/sonarqube/extensions:/opt/sonarqube/extensions
      - ./tmp/sonarqube/logs:/opt/sonarqube/logs
      - ./tmp/sonarqube/temp:/opt/sonarqube/temp

